#!/bin/sh

cat <<EOF > test.cpp
// generated by someone
//generated by someone

#line 1 "parser.rl"

#include <stdio.h>

int main(int argc, char** argv){
  printf("hello\n");
  int a = 5;
  a = a;
  int b;
}
EOF

touch parser.rl
rm -f *.o a.out
gcc test.cpp
